//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int CId { get; set; }
        public string CName { get; set; }
        public string CSection { get; set; }
    }
}
