//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Student_id { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Email { get; set; }
    }
}
